### ISSUE TITLE
Keybind Not Working

### ISSUE THREAD

**Issue by 0x32bit** [vcyzteen/dotbaka#2]
i cant show rofi , terminal, screenshot with using a key ( Windows Key & prtscrn )
>i tried reinstalll dotfiles but still not working

Distro : Artix Linux x86_64 && 5.13.4-artix1-1 ( RUNIT )
Laptops : Acer Aspire V3 371

-.-

**Comment by xealea** [comment]
> i cant show rofi , terminal, screenshot with using a key ( Windows Key & prtscrn )
> 
> > i tried reinstalll dotfiles but still not working
> 
> Distro : Artix Linux x86_64 && 5.13.4-artix1-1 ( RUNIT )
> Laptops : Acer Aspire V3 371
> 
> -.-

Hello @thesky03 thanks for the issue you give
Maybe this issue appears because I moved sxhkd in bspc config. You should try adding sxhkd in .xinitrc and delete sxhkd in bspc config

https://github.com/vcyzteen/dotbaka/blob/513290a5deda875a628fb8651bf909a98e9c230d/.config/bspwm/bspwmrc#L84

Move this line into your .xinitrc
I'm not careful enough to check it and even i delete `sxhkd` in .xinitrc

**Comment by 0x32bit** [comment]
thanks its worked , :D 

Thanks you so much !!
