### ISSUE TITLE
help

### ISSUE THREAD

**Issue by VioletteCrew** [vcyzteen/dotbaka#6]
hi can u help me or tell me how to use mydotfiles or dotbaka on kali

**Comment by xealea** [comment]
> hi can u help me or tell me how to use mydotfiles or dotbaka on kali

Hello, sir. First of all, maybe you can install the required dependencies first. (if you are in kali linux then try to find the dependencies that I show like the command in the readme) 

https://github.com/vcyzteen/dotbaka#dependency-

find it one by one the package ( and install ) i don't know how to install package in kali linux but if it's like debian then type `sudo apt-get install (name package)` without Brackets

If it is already. you can install it like the instructions in the readme. Because all linux almost the same way dotfiles work.

I will close this issue because I only review about bugs or problems that occur. If you want to continue the discussion, you can open the discussion column in the `Discussions` section, sir. Thank you for your attention

NOTE: if you don't know anything about it then you can search about. What are dotfiles and how do they work. Before starting
